# agents.py
# ─────────────────────────────────────────────────────────────
# Node functions for the parallel news analyst graph.
# Contains two nodes:
#   - news_analyst: searches web + writes brief for one topic
#   - report_assembler: combines all briefs into a final report
# Uses Groq (free) for LLM calls and Tavily (free) for web search.
# ─────────────────────────────────────────────────────────────

import os
from datetime import date
from dotenv import load_dotenv
from langchain_groq import ChatGroq
from tavily import TavilyClient

from state import TopicState, OverallState

load_dotenv()

# Initialise the LLM once at module level.
# All five parallel agents share this single client instance —
# it is stateless and safe to call concurrently.
llm = ChatGroq(
    model="llama-3.3-70b-versatile",
    temperature=0.3,
    max_tokens=1024,
)

# Initialise the Tavily search client once at module level.
# Same reasoning: stateless, safe to share across parallel calls.
tavily = TavilyClient(api_key=os.getenv("TAVILY_API_KEY"))


def news_analyst(state: TopicState) -> dict:
    """
    Search the web for a topic and write a structured news brief.

    This is the core parallel worker node. LangGraph runs one instance
    of this function per topic, all simultaneously in the same superstep.
    Each instance receives its own TopicState with exactly one topic.

    The function:
    1. Searches Tavily for recent news on the topic
    2. Extracts the top 3 results
    3. Calls Groq to write a structured brief from the search results
    4. Returns {"briefs": [brief_string]} — a list so operator.add works

    Args:
        state: TopicState containing the topic string for this agent.

    Returns:
        Dict with "briefs" key containing a single-item list with the
        formatted brief. Must be a list so the reducer can concatenate it.
    """
    topic = state["topic"]
    today = date.today().strftime("%B %d, %Y")

    # Step 1: Search the web for recent news on this topic.
    # max_results=3 keeps the context window manageable while still
    # giving the LLM enough material to write a substantive brief.
    search_results = tavily.search(
        query=f"{topic} latest news",
        search_depth="basic",
        max_results=3,
    )

    # Step 2: Extract just the content from each search result.
    # The full search response also includes URLs and metadata,
    # but we only need the text content for the LLM context.
    snippets = []
    for result in search_results.get("results", []):
        title = result.get("title", "")
        content = result.get("content", "")
        snippets.append(f"- {title}: {content}")

    context = "\n".join(snippets)

    # Step 3: Call Groq to write a structured brief from the search results.
    # The prompt asks for a specific format so report_assembler can
    # combine briefs cleanly without further reformatting.
    prompt = f"""You are a professional news analyst writing for an executive briefing.

Date: {today}
Topic: {topic}

Recent search results:
{context}

Write a concise news brief with exactly this format:

**{topic}**
- Key development: [1-2 sentences on the most important recent story]
- Why it matters: [1 sentence on significance]
- Watch for: [1 sentence on what to track next]

Keep the entire brief under 100 words. Be specific, not generic."""

    response = llm.invoke(prompt)

    # Step 4: Return as a list.
    # CRITICAL: return {"briefs": [string]}, not {"briefs": string}.
    # operator.add concatenates lists. If you return a bare string,
    # operator.add joins characters instead of list items — a silent bug.
    return {"briefs": [response.content]}

def report_assembler(state: OverallState) -> dict:
    """
    Combine all individual topic briefs into a formatted final report.

    This node runs once, after all parallel news_analyst agents complete.
    By the time this function is called, state["briefs"] is a fully
    populated list — all five agents have written their contributions
    and the operator.add reducer has concatenated them.

    Args:
        state: OverallState with fully populated briefs list.

    Returns:
        Dict with "report" key containing the final formatted string.
    """
    today = date.today().strftime("%B %d, %Y")
    topic_count = len(state["briefs"])

    # Build the header for the report
    header = f"# Daily Intelligence Briefing\n**{today} | {topic_count} Topics**\n\n---\n\n"

    # Join all briefs with spacing between sections.
    # Each brief is already formatted by news_analyst, so we just
    # concatenate them with a visual separator.
    body = "\n\n---\n\n".join(state["briefs"])

    footer = "\n\n---\n*Generated by Parallel News Analyst · @datasciencebrain*"

    report = header + body + footer

    return {"report": report}
