"""CLI entrypoint: validate a ticker, run the crew, save the research note.

Inputs:  a ticker symbol on the command line, plus optional --sequential.
Outputs: a markdown note at output/<TICKER>-report.md, and a summary on stdout.

    PYTHONPATH=. uv run python -m src.main RELIANCE.NS
    PYTHONPATH=. uv run python -m src.main RELIANCE.NS --sequential
"""

import argparse
import sys
from datetime import datetime

from rich.console import Console
from rich.panel import Panel

from src import yahoo
from src.config import OUTPUT_DIR, report_path, require_keys
from src.crew import Result, run_analysis

DISCLAIMER = (
    "This note was generated by an automated multi-agent system from public data for "
    "educational purposes. It is not investment advice, not a recommendation to buy or "
    "sell any security, and has not been reviewed by a registered adviser. Verify every "
    "figure against primary filings before acting on anything here."
)


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Parallel multi-agent equity research on CrewAI.",
    )
    parser.add_argument(
        "ticker",
        nargs="?",
        default="RELIANCE.NS",
        help="Exact ticker with exchange suffix, e.g. RELIANCE.NS, TCS.NS, AAPL.",
    )
    parser.add_argument(
        "--sequential",
        action="store_true",
        help="Run the four analysts one at a time instead of concurrently.",
    )
    return parser.parse_args()


def _header(ticker: str, result: Result) -> str:
    """Build the metadata block that sits above the model's prose."""
    profile = yahoo.profile(ticker)
    mode = "one at a time" if result.parallel is False else "in parallel"
    generated = datetime.now().strftime("%Y-%m-%d %H:%M")
    return "\n".join(
        [
            f"# {profile['name']} ({ticker})",
            "",
            f"- **Sector:** {profile['sector']} — {profile['industry']}",
            f"- **Price at analysis:** {profile['price']}",
            f"- **Market cap:** {profile['market_cap']}",
            f"- **Generated:** {generated}",
            f"- **Analysts:** 4 specialists run {mode}, then one editor "
            f"({result.seconds:.1f}s total)",
            "",
            "---",
            "",
            "",
        ]
    )


def _save(ticker: str, result: Result) -> str:
    """Write the finished note to output/<TICKER>-report.md."""
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    path = report_path(ticker)
    document = _header(ticker, result) + result.note + f"\n\n---\n\n*{DISCLAIMER}*\n"
    path.write_text(document, encoding="utf-8")
    return str(path)


def main() -> None:
    """Validate, run, save, report."""
    if hasattr(sys.stdout, "reconfigure"):
        # The report and the console output both carry rupee signs and em dashes.
        sys.stdout.reconfigure(encoding="utf-8")

    args = _parse_args()
    ticker = args.ticker.strip().upper()
    console = Console()

    require_keys()

    # Check the symbol resolves before spending a single token on it.
    ok, detail = yahoo.validate(ticker)
    if not ok:
        console.print(f"[bold red]Cannot analyse {ticker}[/]: {detail}")
        raise SystemExit(1)

    mode = "sequentially" if args.sequential else "in parallel"
    console.print(
        Panel(
            f"[bold]{detail}[/] ({ticker})\nFour analysts running {mode}, then the editor.",
            title="stock-research-crew",
            border_style="cyan",
        )
    )

    result = run_analysis(ticker, parallel=not args.sequential)
    path = _save(ticker, result)

    console.print()
    console.print(
        Panel(
            f"Analysts ran {mode} in [bold]{result.seconds:.1f}s[/]\nNote saved to [bold]{path}[/]",
            title="done",
            border_style="green",
        )
    )


if __name__ == "__main__":
    main()
